### ISSUE TITLE
Avoid writing to temporary dir?

### ISSUE THREAD

**Issue by Ocramius** [webimpress/safe-writer#2]
See https://twitter.com/srgmrzv/status/1195378920389898240

Quoting @morozov:

 > `sys_get_temp_dir()` could be avoided too. It potentially adds an unnecessary copy of the file between partitions during the `rename()`, plus on Windows+IIS, it may lead to permission/ownership issues.

 > Please do. Additionally, it doesn't guarantee that the temporary file is removed on failure. Meaning that if you have any issues with the target partition, the temp one will be flooded with temporary files (potential DoS).

**Comment by michalbundyra** [comment]
@Ocramius thanks for reporting, will update it shortly and ping you with PR to review
