### ISSUE TITLE
Why used "& ~umask()"?

### ISSUE THREAD

**Issue by ZVanoZ** [webimpress/safe-writer#66]
https://github.com/webimpress/safe-writer/blob/99ca5bbc8ba652cae54e8c682e3bed1529a61834/src/FileWriter.php#L54

I use "Laminas\ConfigAggregator\ConfigAggregator" in my project.
This library use "Webimpress\SafeWriter\FileWriter" for write cache of config.

1. Test code
```PHP
use Laminas\ConfigAggregator\ArrayProvider;
use Laminas\ConfigAggregator\ConfigAggregator;
use Laminas\ConfigAggregator\LaminasConfigProvider;
use Laminas\ConfigAggregator\PhpFileProvider;

$fileDir = realpath(dirname(__FILE__));
$aggregator = new ConfigAggregator(
    [

        new LaminasConfigProvider('config-json/*.{json,xml,ini,yaml,php}'),
        new PhpFileProvider('config-php/application.config.php'),
        new PhpFileProvider('config-php/development.config.php'),
        new PhpFileProvider('config-php/autoload/{{,*.}global,{,*.}local}.php'),
        new ArrayProvider([
            'fs-points' => [
                '__DIR__' => __DIR__,
                '__FILE__' => __FILE__,
                '$fileDir' => $fileDir,
            ],
            ConfigAggregator::ENABLE_CACHE => true,  // we enable write cache
            ConfigAggregator::CACHE_FILEMODE => 0777 // permissions
        ]),
    ],
    $fileDir . '/tmp/config-cache-mixed.php' // 
);
$config = $aggregator->getMergedConfig();

var_dump($config);
```

2. Check rights:
```bash
$ ls -l html/tests/laminas-config/tmp/config-cache-mixed.php 
-rwxr-xr-x 1 www-data www-data 2999 січ 27 12:21 html/tests/laminas-config/tmp/config-cache-mixed.php
```

**Expected: "-rwxrwxrwx"**
**Actual:  "-rwxr-xr-x"**

**Comment by ZVanoZ** [comment]
Pure test with "Webimpress\SafeWriter" only:
1. Code
```PHP
<?php
require_once "setAutoloader.php";

use Webimpress\SafeWriter\FileWriter;

$fileDir = realpath(dirname(__FILE__));
$filePath = $fileDir . '/tmp/testfile,txt';
FileWriter::writeFile($filePath, 'hello, World!', 0777);
exec("ls -l \"$filePath\"", $output);
var_dump([
    'filePath' => $filePath,
    'permissions' => $output
]);
```
2. Output
```TEXT
/app/www/html/tests/Webimpress-SafeWriter/test-writer.php:12:
array (size=2)
  'filePath' => string '/app/www/html/tests/Webimpress-SafeWriter/tmp/testfile,txt' (length=58)
  'permissions' => 
    array (size=1)
      0 => string '-rwxr-xr-x 1 www-data www-data 13 Jan 27 10:35 /app/www/html/tests/Webimpress-SafeWriter/tmp/testfile,txt' (length=105)
```

**Comment by michalbundyra** [comment]
@ZVanoZ

Thanks for reporting the issue.
This is desired behaviour (also [covered by tests](https://github.com/webimpress/safe-writer/blob/99ca5bbc8ba652cae54e8c682e3bed1529a61834/test/FileWriterTest.php#L47-L70)), we just take into account `umask` from system configuration. Not sure what problem is it causing in your application?

Please bear in mind that this library is used also in https://github.com/Ocramius/ProxyManager/blob/10985759bbf4aeceb13943a09e2b4f07d086c2c8/composer.json#L25 and we didn't see this kind of issue before. Thanks!

**Comment by ZVanoZ** [comment]
Thanks for the annswer.

> what problem is it causing in your application?
My application run in docker container with volume for logs.
So, i can't  delete logs ouside of docker container without root privilegies.
I think i can add my user in www-data group and resolve the problem.
